### ISSUE TITLE
Is there a way around log4j.properties at initialization?

### ISSUE THREAD

**Issue by venantius** [malcolmsparks/clj-logging-config#27]
I'm noticing that a lot of libraries my app depends on tend to do some sort of log initialization that doesn't play nicely with clj-logging-config at import time.

For instance: right now, I've got an app with a method that configures logging as follows:

```clojure
(defn set-logging-defaults
  "Set the logging level for the application root"
  []
  (set-loggers! :root {:level :info
                       :out :console
                       :pattern "[%p] %d{MM-dd-yyyy HH:mm:ss} | %m%n"}))
```

This method then gets called in a configuration method before the server starts up, e.g.:
```clojure
(defn -main []
  (init/configure)
  (server/run-server #'app {:port (Integer. (or (System/getenv "PORT") "8080"))
                            :join? false}))
```

However, I have korma.db on the import path for my app's `core` namespace. The import happens before the logging configuration is executed, and I end up with the following when I launch my app (removing the `korma.db` import immediately removes this WARN):
```
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
Is there a way around this that I haven't figured out that doesn't rely on either creating a log4j.properties file or executing `(set-logging-defaults)` at import time? In general, what's the recommended practice here?

**Comment by binarykitchen** [comment]
Good question, same here, I would like to get rid of log4j.properties ...

**Comment by venantius** [comment]
Unfortunately, after a fairly long period of trying to figure this out, I don't think there's any real best practice here that actually works other than using a log4j.properties file. You could write all sorts of injections to handle the logging if you wanted, but it's a lot of headache for not a lot of mileage. My advice is just to write a log4j.properties file and be done with it. I'm closing this issue.

**Comment by binarykitchen** [comment]
Totally understand. The problem is that our project root folder is way too declustered with too many root folders. For example `/resource` only contains one `log4j.properties`. That's why I am trying to get rid off it. Any chance  `log4j.properties` can be moved to another folder or can be configured in a lein's project.clj?

**Comment by venantius** [comment]
I think you can keep in a few different places (I forget, for instance, if you can keep it in `/src` or not). You might want to look into something like the following in your `project.clj` as well:  `:jvm-opts ["-server" "-Dlog4j.configuration=my-special-log4j-properties-filename.properties"]`

**Comment by binarykitchen** [comment]
Ah, wonderful. That's all I wanted. Many thanks!

**Comment by jwymanm** [comment]
I know this was closed but I was able to get mongodb v3 to use the :root logging settings without resorting to log4j.properties. In a recent post they mentioned a bug in set-logger! so you use set-loggers! :root {:level ... :out ...}
